version: '3'

services:
  postgres:
    image: postgres
    container_name: postgresMCCM
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminMCCM
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.root
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "127.0.0.1:5433:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backendMCCM
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgres:5432/postgres",
            "spring.datasource.username" : "postgres",
            "spring.datasource.password" : "postgres",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres-data: